### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by PeterWilsono** [aspuru-guzik-group/GA#5]
I am unable to resolve 'RuntimeError An attack has been made to start a new process before the current process has finished its bootstrapping phase.' Requesting assistance with this issue！

**Comment by akshat998** [comment]
Hello,

This issue can sometimes be specific to the operating system. Could you please specify which system you're using? This repository was tested on Ubuntu, and knowing your system might help in diagnosing the problem.

Additionally, while addressing this issue, you might be interested in exploring JANUS, an algorithm that's known for its efficiency and improved performance in similar contexts (an improvement of this algorithm). Here's a link for more information and potential insights that might be relevant to your situation: https://github.com/aspuru-guzik-group/JANUS

Hope this helps and looking forward to your response regarding the system details! :)

**Comment by PeterWilsono** [comment]
My device is&nbsp; Windows 10 system&nbsp;




PeterWilson
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aspuru-guzik-group/GA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 中午1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aspuru-guzik-group/GA] RuntimeError (Issue #5)





 
Hello,
 
This issue can sometimes be specific to the operating system. Could you please specify which system you're using? This repository was tested on Ubuntu, and knowing your system might help in diagnosing the problem.
 
Additionally, while addressing this issue, you might be interested in exploring JANUS, an algorithm that's known for its efficiency and improved performance in similar contexts (an improvement of this algorithm). Here's a link for more information and potential insights that might be relevant to your situation: https://github.com/aspuru-guzik-group/JANUS
 
Hope this helps and looking forward to your response regarding the system details! :)

**Comment by PeterWilsono** [comment]
I am very interested in adding discriminators to genetic algorithms to solve problems, so I hope to run this code on my device, which will be very helpful!




PeterWilson
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aspuru-guzik-group/GA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 中午1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aspuru-guzik-group/GA] RuntimeError (Issue #5)





 
Hello,
 
This issue can sometimes be specific to the operating system. Could you please specify which system you're using? This repository was tested on Ubuntu, and knowing your system might help in diagnosing the problem.
 
Additionally, while addressing this issue, you might be interested in exploring JANUS, an algorithm that's known for its efficiency and improved performance in similar contexts (an improvement of this algorithm). Here's a link for more information and potential insights that might be relevant to your situation: https://github.com/aspuru-guzik-group/JANUS
 
Hope this helps and looking forward to your response regarding the system details! :)

**Comment by akshat998** [comment]
Hello,

This makes sense. Python's inherent parallelization capability, facilitated by multiprocessing, does not receive full support on Windows systems. Could you consider using a Linux-based system, such as Mac or Ubuntu, possibly on a cluster?

Alternatively, you could eliminate multiprocessing from the code, replacing it with for-loops. Be aware, though, that this change will result in slower execution than the current implementation.

You can also use Google Colab with JANUS (as the code in JANUS is pip-intallable) :) 

Regards
Akshat

**Comment by PeterWilsono** [comment]
Thank you for your reply. I cannot fully understand this code, but I am very interested in using neural networks as discriminators to enhance genetic algorithms.&nbsp;


How can I learn the logic behind this? I only need to look at the discriminator file.


&nbsp;I would also like to ask for your opinion


PeterWilson
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aspuru-guzik-group/GA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 中午1:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aspuru-guzik-group/GA] RuntimeError (Issue #5)





 
Hello,
 
This makes sense. Python's inherent parallelization capability, facilitated by multiprocessing, does not receive full support on Windows systems. Could you consider using a Linux-based system, such as Mac or Ubuntu, possibly on a cluster?
 
Alternatively, you could eliminate multiprocessing from the code, replacing it with for-loops. Be aware, though, that this change will result in slower execution than the current implementation.
 
You can also use Google Colab with JANUS (as the code in JANUS is pip-intallable) :)
 
Regards
 Akshat

**Comment by akshat998** [comment]
Hi Peter, 

Absolutely! Definitely make sure you understand the paper first, then, look at the discriminator implementation, along with specifically how it's used in the fitness evaluations. 

Good luck! Feel free to re-open/create new issues if you have questions :)
